### PR TITLE
Use apiaryio homebrew formulae tap

### LINKED ISSUE #214: Remove head-only requirement from homebrew package
I've already been bitten by this once when the library was updated to 1.0; my scripts were built against 0.x library and it took forever to figure out why they were broken on a new teammate's Mac.

Tried installing from a stable release but got the following error:

```
$ brew install https://raw.githubusercontent.com/apiaryio/drafter/v2.1.2/tools/homebrew/drafter.rb
######################################################################## 100.0%
Error: drafter is a head-only formula
Install with `brew install --HEAD drafter`
```

I agree with [these folks](https://github.com/Homebrew/homebrew-head-only#why-is-head-only-bad) on the matter—as long as this package is head-only, I can't get consistent results out of any scripts I write that use drafter.

### PR DESCRIPTION
**Pull request by kylef**
This change will also allow us to provide a non-HEAD homebrew formula that uses the release tarball which allows `brew upgrade` to actually work for drafter and makes it easier for users to have multiple versions of Drafter installed using `brew switch` (`brew switch drafter 3.2.7` eg). This uses automation to update the out of repo formula in CI by proposing a PR back to the repo (so the CI on that repo confirms the formula builds and allows someone to further merge that PR).

The first PR refactors the existing release script to break it into functions, so it was easier to test each step (can comment out function invocation) and make it easier to manage going forward. Recommended to review per commit.

Obligatory testing PR: https://github.com/apiaryio/homebrew-formulae/pull/8

#### Dependencies

- [x] Update the homebrew formula https://github.com/apiaryio/homebrew-formulae/pull/7
- [x] Allow `ApiaryBot` GitHub user to have write access to the `homebrew-formulae` repo. This user is already configured in `GITHUB_TOKEN` for the release tarball upload.

@abtris would appreciate your eyes here to make sure this is okay. We can use similar script in blackbelt too. Need to be careful that `$CREDENTIALS` never makes it to stdout.

#### Usage

The output of the command looks like the following (note it fails as user doesn't have perms yet):

```
$ ./tools/release.sh
Cloning into 'homebrew-formulae'...
remote: Counting objects: 46, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 46 (delta 6), reused 20 (delta 2), pack-reused 15
Unpacking objects: 100% (46/46), done.
M	Formula/drafter.rb
Switched to a new branch 'drafter-v4.0.0-pre.0'
diff --git a/Formula/drafter.rb b/Formula/drafter.rb
index 9567b62..d257c56 100644
--- a/Formula/drafter.rb
+++ b/Formula/drafter.rb
@@ -1,8 +1,8 @@
 class Drafter < Formula
   desc 'Snowcrash parser harness'
   homepage 'http://apiblueprint.org'
-  url 'https://github.com/apiaryio/drafter/releases/download/v2.1.2/drafter-v2.1.2.tar.gz'
-  sha256 '2e1ea1b34ec817e917a050e50252f492aff308b0640b075a6b7f2fcf6a996810'
+  url 'https://github.com/apiaryio/drafter/releases/download/v4.0.0-pre.0/drafter-v4.0.0-pre.0.tar.gz'
+  sha256 '3dc5b082fe8b9773873b1103c88a28366f1ea0965d54249f762f621f818b4da7'
   head 'https://github.com/apiaryio/drafter.git'

   def install
[drafter-v4.0.0-pre.0 a73eb60] feat: Update drafter to v4.0.0-pre.0
 1 file changed, 2 insertions(+), 2 deletions(-)
remote: Permission to apiaryio/homebrew-formulae.git denied to ApiaryBot.
fatal: unable to access 'https://github.com/apiaryio/homebrew-formulae.git/': The requested URL returned error: 403
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "PullRequest",
      "field": "head",
      "code": "invalid"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"
}
```

Fixes #214
Closes #215

### CODE REVIEW

**Comment by SMillerDev** [comment]
You might be better off referencing and sending PRs to homebrew core. https://github.com/Homebrew/homebrew-core/blob/master/Formula/drafter.rb

**Comment by abtris** [comment]
I think we can use `.netrc` in script that can prevent some leaking info better. What do you think @kylef ?

**Comment by kylef** [comment]
After some further discussions internally. We want to avoid external CI systems being able to publish back to our GitHub repositories for security reasons so I would avoid this approach.

Given that Homebrew core now contains drafter it isn't needed to maintain our own formula repository for Drafter. There is inherent risk that changes to Drafter could cause the Formula to break I don't think it makes sense to create a pull request as a bot to an external repository that we won't know if it will work.

**Comment by SMillerDev** [comment]
You're always very welcome to make homebrew pull requests as a human 😃

**Pull request closed without merging**
