### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by kylef**
This releases 3.0.0 of Drafter. I've also updated the homebrew formula to drafter library and header.

### Breaking

* Drafter now uses C++11.

  The following compiler versions are supported:

  * Microsoft Visual C++ 2013 or higher
  * GCC 4.8 or higher
  * Clang 3.5 or higher

### Enhancements

* Drafter now provides a full C and C++ API interface, you may now validate, parse and serialize an API Blueprint. Please see `drafter.h` header for full API documentation.
* Improve error messages for a few blueprint errors

### Bug Fixes

* Correctly render named primitive types when used as a nested or member type such as `items (array[Other Type])` in JSON.  
  [#312](https://github.com/apiaryio/drafter/issues/312)

* Fixes an issue where defining an implicit object data structure would raise an invalid syntax warning and not be parsed.  
  [#318](https://github.com/apiaryio/drafter/issues/318)

* Prevent causing an infinite loop when parsing a resource which inherits from itself.  
  [#328](https://github.com/apiaryio/drafter/issues/328)

* Correctly parse object samples within arrays.  
  [#246](https://github.com/apiaryio/drafter/issues/246)

* Correctly render JSON Schema when `fixed` is used on attributes section or named type  
  [mson#60](https://github.com/apiaryio/mson/issues/60)

### CODE REVIEW

**Comment by kylef** [comment]
Issued a "Do not merge" because I want to get https://github.com/apiaryio/protagonist/pull/157 passing CI first incase we need to change anything here.

**Comment by kylef** [comment]
### Ruby FFI

Using Drafter 3 when `libdrafter` is installed into your system. You can use Drafter pretty easy using FFI.

```ruby
require 'ffi'

module Drafter
  extend FFI::Library
  ffi_lib 'drafter'

  attach_function :drafter_version_string, [], :string
  attach_function :drafter_version, [], :int

  attach_function :drafter_check_blueprint, [:string], :pointer
  attach_function :drafter_free_result, [:pointer], :void
end

puts Drafter.drafter_version_string
puts Drafter.drafter_version

blueprint = <<-DOC
# My API
## GET /
DOC

result = Drafter.drafter_check_blueprint(blueprint)
if result
  puts 'good'
else
  puts 'bad'
  Drafter.drafter_free_result(result)
end
```

```shell
$ ruby drafter.rb
v2.3.1
131841
good
```

**Comment by w-vi** [comment]
I guess I should write one for python using ctypes and cffi

**Comment by pksunkara** [comment]
@kylef Do you think we should update redsnow?

**Comment by pksunkara** [comment]
@kylef Please tag and release.

**Comment by jayniz** [comment]
@pksunkara 
> @kylef Do you think we should update redsnow?

yes! yes! :)

**Pull request merged**
