### PR TITLE
Added request parameters to refract

### PR DESCRIPTION
**Pull request by pksunkara**
Depends on apiaryio/snowcrash#366 and apiaryio/snowcrash#367.

Need to update snowcrash submodule in this PR once the above PRs are merged.

### CODE REVIEW

**Comment by pksunkara** [comment]
This is ready to be reviewed and merged. /cc @w-vi @klokane

**Comment by kylef** [comment]
:+1: Looks good, but the tests are failing due to other changes in Snowcrash.

**Comment by pksunkara** [comment]
@kylef Updated.

**Comment by w-vi** [comment]
Looking at the circular reference test, the json and schema are not correctly rendered. I think its good to go but we should fix these in next sprint.

**Comment by pksunkara** [comment]
@w-vi Can you create an issue on drafter if you have an example at hand? We should track all this stuff.

**Comment by w-vi** [comment]
Sure,  just doing it.

**Pull request merged**
