### PR TITLE
starting work on #117

### PR DESCRIPTION
**Pull request by obihann**

### CODE REVIEW

**Comment by klokane** [comment]
@obihann hi, can you please deliver tests?

**Comment by obihann** [comment]
@klokane I'm still working on this (and to be honest could use some help), but I will add the tests as soon as the rest is in place.

**Comment by klokane** [comment]
@obihan we really appreciate your source code patches, and we will be happy to help you.
If you would like some help or guidance just ping me (or @pksunkara) on your branch

But I would like to kindly ask you to create pull requests only when they are ready for code review.

**Comment by obihann** [comment]
@klokane Thanks for the message, I probably jump the gun on these pull requests, I'll be sure to wait until they are done and start tagging you and @pksunkara when I'm stuck.

Thanks!

**Comment by klokane** [comment]
@obihann you are welcome. 
Additional I would like to please you add comment to related issue (if exists) with link on your branch.

**Comment by obihann** [comment]
@klokane I've been trying to do that actually, #117 should have some comments from me including what I think the problem is and where I got stuck. If they don't make sense or are in the wrong place let me know and I can reword them or move them.

I'm glad I can help you guys on this, the project I (and the company i work for) is building uses blueprint documentation heavily and though we have a few concerns we really love it. The concerns we have are already logged as tickets and I'm trying to help you guys as much as I can so the tool gets even better. I hope I'm not causing too much of a headache for you.

**Pull request closed without merging**
