### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by klokane**
Fixed memory leaks on
- create description
- double registration of Named Types in AST branch

### CODE REVIEW

**Comment by kylef** [comment]
I have the one question, but otherwise the changes look good to me. Would appreciate if someone else could give a :+1: too.

:+1:

**Comment by w-vi** [comment]
The changes look good but I have to admit that I don't see where the memory leak actually was. @klokane

**Comment by klokane** [comment]
@w-vi second one is more complex, But in general while was call `WrapResult()` with `AST` type, it come later to `WrapBlueprint()`  

They both made `RegisterNamedTypes()` and no where was checked if named object is already registrated. 
So I split it into two diferent "run branches" and clarify interface by removing unneeded functions

**Comment by w-vi** [comment]
@klokane OK now I get it ... nice job

**Comment by pksunkara** [comment]
:+1:

**Pull request merged**
