### PR TITLE
Resolve sourcemaps for throws in drafter

### PR DESCRIPTION
**Pull request by klokane**
Need to rebased on current master.

### CODE REVIEW

**Comment by klokane** [comment]
First merge #266

**Comment by kylef** [comment]
:+1:

**Comment by klokane** [comment]
Rebased on master push forced

**Comment by pksunkara** [comment]
@klokane @w-vi This is great work guys. But I specifically asked to use `generateSourceMap` name in our codebase everywhere instead of `exportSourceMap`.

I will be making a PR for this.

**Pull request merged**
