### PR TITLE
Prepare v0.1.7 release

### PR DESCRIPTION
**Pull request by pksunkara**
This PR updates snowcrash to v1.0.6

### CODE REVIEW

**Comment by w-vi** [comment]
It's 1.0.7 isn't it?

**Comment by pksunkara** [comment]
No, snowcrash is v1.0.6. https://github.com/apiaryio/snowcrash/releases/tag/v1.0.6

Drafter new version is v0.1.7

**Comment by pksunkara** [comment]
Oh, let me rename the commit then. Thanks. :+1:

**Comment by w-vi** [comment]
@pksunkara Looks good, once tests are done feel free to merge

**Pull request merged**
