### PR TITLE
Merge snowcrash as a subtree

### PR DESCRIPTION
**Pull request by kylef**
TODO:

- Setup Appveyor CI
- Setup Travis CI

### CODE REVIEW

**Comment by kylef** [comment]
I'd also propose we merge sundown and markdown-parser in too. Any objections?

**Comment by pksunkara** [comment]
Let's not merge sundown.

**Comment by w-vi** [comment]
Why not?

**Comment by pksunkara** [comment]
Because sundown is a fork of an existing project while the others are not.

**Comment by w-vi** [comment]
So? I don't understand. Look at for example https://github.com/nodejs/node/tree/master/deps all dependencies are in the tree.

**Comment by w-vi** [comment]
Is it going to happen or not?

**Comment by kylef** [comment]
@w-vi Yes, just closing this PR as this needs to be re-done from current masters and finished up. This will be scheduled in a sprint soon.

**Pull request closed without merging**
