### PR TITLE
Remove MSON AST related code

### PR DESCRIPTION
**Pull request by pksunkara**
Long time coming.

### CODE REVIEW

**Comment by pksunkara** [comment]
This is a breaking change. So, we should do this along with public API cleanup.

**Comment by pksunkara** [comment]
Updated.

**Comment by pksunkara** [comment]
This is passing. But let's do a release first before merging this.

**Comment by pksunkara** [comment]
Please don't merge master branches into PR branches. I already rebased after the valgrind fix.

Github and it's stupid UI.

**Comment by w-vi** [comment]
@pksunkara rebase and lets merge it if we are not releasing

**Comment by pksunkara** [comment]
Why do you need a rebase? This is mergable to master. Github is stupid to introduce this out-of-date stuff.

**Comment by w-vi** [comment]
True, I forgot what has been changed.

**Pull request merged**
