### PR TITLE
Add convenience PrintVisitor

### PR DESCRIPTION
**Pull request by w-vi**
PrintVisitor is a helper visitor, it just prints the refract element and
its sybelements to any `ostream` provided. Default is `std::cout`

### CODE REVIEW

**Comment by w-vi** [comment]
@klokane please have a look, if it is good enough for starters.

**Comment by klokane** [comment]
Nice. Just please use `camelCase` naming convention for PrintVisitor methods

**Comment by klokane** [comment]
And do not use underscore prefixed members. Just formality, but wide used

**Comment by w-vi** [comment]
@klokane I'm done

**Pull request merged**
