### PR TITLE
Add Drafter-php as binding for the PHP language

### PR DESCRIPTION
**Pull request by hendrikmaus**
I recently created [Drafter-php](https://github.com/hendrikmaus/drafter-php) as wrapper around the Drafter command line tool.

The package can be installed using composer.
Drafter command line tool has to be installed aside to it. The readme contains some basic instructions on how to do that with composer, but first of all references the Drafter repositories installation guides.

If you consider this a binding, this pull request would add it to the readme.

I am looking forward to your feedback.

Cheers,
Hendrik

### CODE REVIEW

**Comment by pksunkara** [comment]
@hendrikmaus We love this, but this is just a wrapper around the CLI tool. This does not use the native c++/c-interface like the other bindings (protagonist, redsnow) publicised in README does.

I am a little hesitant to merge this. Maybe this should go to some kind of wiki page but not the README.

**Comment by zdne** [comment]
Thanks @hendrikmaus – this is awesome! 

@pksunkara 

> c++/c-interface like the other bindings (protagonist, redsnow) publicised in README does

I believe that is OK. I would still add this to the README. If you really want to differentiate that I would add it to a new section of README called something like "CLI Binding"  but I think that just makes it harder to think about. 

So for me it is OK as it is now.

**Comment by hendrikmaus** [comment]
Glad you like it, guys.
I investigated a bit, but I did not find a way to natively bind the c or c++ interface in a way I would be comfortable to put out and maintain. It would always involve building a php extension either in plain vanilla c, php-cpp, long broken ffi (pecl) or swig. a simple wrapper around the cli tool made the most sense for me.

**Comment by pksunkara** [comment]
@hendrikmaus Can you make a `### CLI Wrapper` subheader under the `Bindings` header and list this under there?

I would like to differentiate between native bindings and CLI wrappers as some people would like to use different things based on their use cases. Thanks.

**Comment by hendrikmaus** [comment]
@pksunkara added the subheader, cheers

**Comment by pksunkara** [comment]
Thanks :smile:

**Pull request merged**
