### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by goganchic**
This code is doing nothing useful, I think it's some kind of legacy.

### CODE REVIEW

**Comment by pksunkara** [comment]
Pasting my comment from before, I am not sure about this.

**Comment by goganchic** [comment]
@pksunkara why are you not sure?

**Comment by pksunkara** [comment]
Yes please split the PR.

**Comment by pksunkara** [comment]
@goganchic Can you make a separate PR with the other commit you removed from here?

**Comment by goganchic** [comment]
@pksunkara would you please tell me if there are some problems preventing us from merging this PR?

**Comment by pksunkara** [comment]
@goganchic Thanks. Had to take a lot of time to understand why that was there in the first place.

**Pull request merged**
