### PR TITLE
Fix #318

### LINKED ISSUE #318: Non valid behavior for attribute `- key: value (object)`
For following blueprint
```
# GET /
- Response 200 (application/json)
    - Attribute (A)

# Data Structures

## A
- myObject: abc (object)
```

I will receive message
```
warning: (1)  unable to render JSON/JSONSchema. Invalid member type of object in MSON definition :11:32
```

Expected behavior is report invalid syntax for definition `- myObject: abc (object)`

### PR DESCRIPTION
**Pull request by klokane**
warn on property of type `object` with string value definition e.g:
- key: value (object)

### CODE REVIEW

**Comment by pksunkara** [comment]
Can you please add a unit test to https://github.com/apiaryio/snowcrash/pull/387 before we merge this? Thanks.

**Comment by klokane** [comment]
Another duplicit test?

Additional, with standard `MSONPropertyMemberParser` it will not work because it need context.
And in this case it is not unit test, it will not test just unit.
It will be next integration test...

**Comment by pksunkara** [comment]
Can you update the drafter submodule? And also, you can remove the test from here if you want.

**Comment by klokane** [comment]
Updated,
Test should not be removed from there, because
- it testing more difrerent cases
- it testing if warnings are in result
- changes are related to specialization of `MoveFirstValueToSample` (changed in previous PR)

**Pull request merged**
