### PR TITLE
Release 3.2.2

### PR DESCRIPTION
**Pull request by kylef**
### Bug Fixes

* Ensure that escaped property names in MSON are not treated as markdown.
  [snowcrash#422](https://github.com/apiaryio/snowcrash/pull/422)

### CODE REVIEW

**Comment by w-vi** [comment]
@kylef  what are the x,y,t2 etc files for?

**Comment by kylef** [comment]
@w-vi Not sure why that was staged, I've fixed the PR.

**Comment by pksunkara** [comment]
@w-vi Can you update the snowcrash here?

**Comment by pksunkara** [comment]
Tested it, works greatly

**Pull request merged**
