### PR TITLE
Fixed ExtendElement merge strategy for RefElement member (bug #419)

### LINKED ISSUE #419: JSON is generated in wrong order for override mixins
For following blueprint

```apib
# GET /

+ Response 200 (application/json)

    + Attributes (object)
        + tasks (array, optional)
            + (Task)  
                + name: `one` (string, required)
            + (Task)
                + Include Status
                + name: `two` (string, required)

# Data Structures

## Status
+ status (enum[string])
    + `CREATED`         
    + `QUEUED`
    + `RUNNING`
    + `FINISHED`
    + `ERROR`

## Task (object)
+ Include Status
+ name (string, required) - Name of task
```

Is generated following JSON:

```son
{
  "tasks": [
    {
      "status": "CREATED",
      "name": "one"
    },
    {
      "name": "two",
      "status": "CREATED"
    }
  ]
}
```

`Status` for second task should be in same order like for first task

### PR DESCRIPTION
**Pull request by tjanc**
- added fixtures for #419 
- fixed #419 
- updated .gitignore

### CODE REVIEW

**Comment by w-vi** [comment]
Why the gitignore change, what is swp and swo?

**Comment by pksunkara** [comment]
vim temporary files.

**Comment by klokane** [comment]
:+1:

**Comment by w-vi** [comment]
Editor specific stuff should be in your own global gitignore because otherwise all the projects you touch you pollute with your specific settings.

**Comment by w-vi** [comment]
See for example mine where all the emacs specific stuff is ignored for any repo I work with. 
https://gist.github.com/w-vi/ba18bfc59c32d93bc565265081679d54

**Comment by tjanc** [comment]
If the project-specific gitignore isn't supposed to hold these entries, then the whole last block in the file is basically "pollution", am I right?

**Comment by w-vi** [comment]
Yes, you are tight, most of it is pollution and should not be there.

**Pull request merged**
